### ISSUE TITLE
Error while muting in voice channel

### ISSUE THREAD

**Issue by Redblueflame** [WamWooWam/Unicord#20]
I got an error while muting while connecting.

```
System.InvalidOperationException
  HResult=0x8000000E
  Message=A method was called at an unexpected time.

A method was called at an unexpected time.

  Source=Windows
  StackTrace:
   at Windows.ApplicationModel.AppService.AppServiceConnection.SendMessageAsync(ValueSet message)
   at Unicord.Universal.Voice.VoiceConnectionModel.<SendRequestAsync>d__33.MoveNext() in D:\Dev\Unicord\Unicord.Universal\Voice\VoiceConnectionModel.cs:line 177
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Unicord.Universal.Voice.VoiceConnectionModel.<ToggleMuteAsync>d__30.MoveNext() in D:\Dev\Unicord\Unicord.Universal\Voice\VoiceConnectionModel.cs:line 160
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Unicord.Universal.Voice.VoiceConnectionModel.<OnPropertyChanged>d__27.MoveNext() in D:\Dev\Unicord\Unicord.Universal\Voice\VoiceConnectionModel.cs:line 77
```

**Comment by WamWooWam** [comment]
This seems to be simply because you weren’t connected when trying to communicate with the background service. This should be a simple fix
